---

- name: LabBot deployment
  hosts: all
  become: true
  module_defaults:
    community.docker.docker_container:
      restart_policy: always
      state: started
      comparisons:
        '*': strict
        env: allow_more_present
  roles: [labbot]
